name: Hospital-MS-DB

services:
  postgres:
    image: postgres:16-alpine3.20
    ports: 
      - "5432:5432" 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=hospital_ms

